apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: oziw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oziw
    app.kubernetes.io/part-of: byoc-app-wnhm
  name: oziw
spec:
  rules:
  - host: oziw-byoc-jzop-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-kxb8g.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: oziw
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
